apiVersion: v1
kind: Service
metadata:
  name: ue5-gameserver-service
spec:
  type: NodePort
  selector:
    app: ue5-gameserver
  ports:
    - name: game
      protocol: UDP
      port: 7777
      targetPort: 7777
    - name: beacon
      protocol: TCP
      port: 15000
      targetPort: 15000
